"""Risk-policy lifecycle: create, update, and show.

Updates are a two-call flow: a proposal with a diff that flags loosening changes,
then a write only when confirm=True. Every change is versioned and audited.
"""

from __future__ import annotations

import copy
import hashlib
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from . import audit, messages
from .models import Policy, PolicyDiffEntry, PolicyResult
from .store import atomic_write_text, history_dir, resolve_policy_path

PolicyInput = Policy | dict | None


class PolicyLoadError(Exception):
    """A policy file exists but could not be parsed or validated.

    The message is deliberately generic (path only): the underlying parser error
    can echo file contents, and a caller-controlled ``policy_path`` must not become
    a way to read arbitrary file data back through an error string.
    """

    def __init__(self, path: str) -> None:
        self.path = path
        super().__init__(f"policy file at {path} could not be read or validated")

# --------------------------------------------------------------------------- #
# Presets: illustrative starting defaults the user's explicit fields override. #
# --------------------------------------------------------------------------- #

PRESETS: dict[str, dict[str, Any]] = {
    "conservative": {
        "limits": {"max_single_position_pct": 10, "warn_at_utilization": 75},
        "asset_rules": {"crypto": "block", "options": "block", "margin": "block"},
        "order_rules": {"max_order_pct_of_portfolio": 5, "min_cash_pct": 10},
        "data_rules": {"max_snapshot_age_hours": 24},
    },
    "balanced": {
        "limits": {"max_single_position_pct": 20, "warn_at_utilization": 80},
        "asset_rules": {"crypto": "warn", "options": "warn", "margin": "block"},
        "order_rules": {"max_order_pct_of_portfolio": 10, "min_cash_pct": 5},
        "data_rules": {"max_snapshot_age_hours": 24},
    },
    "aggressive": {
        "limits": {"max_single_position_pct": 35, "warn_at_utilization": 85},
        "asset_rules": {"crypto": "allow", "options": "allow", "margin": "warn"},
        "order_rules": {"max_order_pct_of_portfolio": 20, "min_cash_pct": 0},
        "data_rules": {"max_snapshot_age_hours": 24},
    },
}
DEFAULT_PRESET = "balanced"


# --------------------------------------------------------------------------- #
# Serialization helpers                                                       #
# --------------------------------------------------------------------------- #


def _num(v: float) -> int | float:
    """Render 25.0 as 25 for clean YAML, but keep genuine decimals."""
    f = float(v)
    return int(f) if f == int(f) else f


def policy_to_dict(p: Policy) -> dict[str, Any]:
    """Ordered, YAML-safe dict. Optional numeric limits are omitted when unset."""
    d: dict[str, Any] = {
        "schema_version": p.schema_version,
        "revision": p.revision,
        "preset": p.preset,
        "created_at": p.created_at,
        "updated_at": p.updated_at,
    }
    if p.notes is not None:
        d["notes"] = p.notes

    limits: dict[str, Any] = {}
    if p.limits.max_single_position_pct is not None:
        limits["max_single_position_pct"] = _num(p.limits.max_single_position_pct)
    limits["max_sector_pct"] = {k: _num(v) for k, v in sorted(p.limits.max_sector_pct.items())}
    limits["max_tag_pct"] = {k: _num(v) for k, v in sorted(p.limits.max_tag_pct.items())}
    limits["max_asset_class_pct"] = {
        k: _num(v) for k, v in sorted(p.limits.max_asset_class_pct.items())
    }
    limits["warn_at_utilization"] = _num(p.limits.warn_at_utilization)
    d["limits"] = limits

    d["asset_rules"] = {
        "crypto": p.asset_rules.crypto.value,
        "options": p.asset_rules.options.value,
        "margin": p.asset_rules.margin.value,
    }

    order_rules: dict[str, Any] = {}
    if p.order_rules.max_order_pct_of_portfolio is not None:
        order_rules["max_order_pct_of_portfolio"] = _num(p.order_rules.max_order_pct_of_portfolio)
    if p.order_rules.max_order_value is not None:
        order_rules["max_order_value"] = _num(p.order_rules.max_order_value)
    if p.order_rules.min_cash_pct is not None:
        order_rules["min_cash_pct"] = _num(p.order_rules.min_cash_pct)
    d["order_rules"] = order_rules

    d["restricted"] = {
        "never_trade": list(p.restricted.never_trade),
        "warn_list": list(p.restricted.warn_list),
    }
    d["data_rules"] = {"max_snapshot_age_hours": _num(p.data_rules.max_snapshot_age_hours)}
    return d


def render_yaml(p: Policy) -> str:
    header = (
        "# AgentRisk policy file. Generated by generate_risk_policy; you can edit it by hand.\n"
        "# Percentages are 0-100. Absence of a limit means that limit is not enforced.\n"
    )
    body = yaml.safe_dump(policy_to_dict(p), sort_keys=False, default_flow_style=False)
    return header + body


def policy_sha256(p: Policy) -> str:
    return hashlib.sha256(render_yaml(p).encode("utf-8")).hexdigest()


def coerce_policy(policy: PolicyInput) -> Policy:
    if isinstance(policy, Policy):
        return policy
    if isinstance(policy, dict):
        return Policy(**policy)
    raise TypeError("policy must be a Policy, a dict, or None")


# --------------------------------------------------------------------------- #
# Resolution (used by check_trade_risk / analyze_portfolio_risk)              #
# --------------------------------------------------------------------------- #


def resolve_policy(
    policy: PolicyInput = None,
    policy_path: str | None = None,
    home: str | None = None,
) -> tuple[Policy | None, dict[str, Any]]:
    """Inline policy > explicit path > default location. Returns (policy, meta)."""
    if policy is not None:
        pol = coerce_policy(policy)
        return pol, {"source": "inline", "path": None, "revision": pol.revision,
                     "sha256": policy_sha256(pol)}

    path = resolve_policy_path(policy_path, home)
    if path.exists():
        try:
            data = yaml.safe_load(path.read_text("utf-8")) or {}
            pol = Policy(**data)
        except Exception as exc:  # noqa: BLE001 - never surface raw file contents
            raise PolicyLoadError(str(path)) from exc
        return pol, {"source": "file", "path": str(path), "revision": pol.revision,
                     "sha256": policy_sha256(pol)}

    return None, {"source": "none", "path": str(path), "revision": None, "sha256": None}


# --------------------------------------------------------------------------- #
# Diffing                                                                     #
# --------------------------------------------------------------------------- #


def _flatten(p: Policy) -> dict[str, Any]:
    flat: dict[str, Any] = {
        "limits.max_single_position_pct": p.limits.max_single_position_pct,
        "limits.warn_at_utilization": p.limits.warn_at_utilization,
        "asset_rules.crypto": p.asset_rules.crypto.value,
        "asset_rules.options": p.asset_rules.options.value,
        "asset_rules.margin": p.asset_rules.margin.value,
        "order_rules.max_order_pct_of_portfolio": p.order_rules.max_order_pct_of_portfolio,
        "order_rules.max_order_value": p.order_rules.max_order_value,
        "order_rules.min_cash_pct": p.order_rules.min_cash_pct,
        "data_rules.max_snapshot_age_hours": p.data_rules.max_snapshot_age_hours,
    }
    for bucket_attr, prefix in (
        (p.limits.max_sector_pct, "limits.max_sector_pct"),
        (p.limits.max_tag_pct, "limits.max_tag_pct"),
        (p.limits.max_asset_class_pct, "limits.max_asset_class_pct"),
    ):
        for k, v in bucket_attr.items():
            flat[f"{prefix}.{k}"] = v
    return flat


_ASSET_ORDER = {"allow": 0, "warn": 1, "block": 2}


def _tightness(key: str, val: Any) -> float:
    if val is None:
        return float("-inf")
    if key.startswith("asset_rules."):
        return float(_ASSET_ORDER[val])
    if "min_cash" in key:
        return float(val)
    # everything else (caps, warn_at_utilization, snapshot age): lower value = tighter
    return -float(val)


def _classify(key: str, old: Any, new: Any) -> str:
    t_old, t_new = _tightness(key, old), _tightness(key, new)
    if t_new > t_old:
        return "tightening"
    if t_new < t_old:
        return "loosening"
    return "neutral"


def diff_policies(old: Policy, new: Policy) -> list[PolicyDiffEntry]:
    entries: list[PolicyDiffEntry] = []
    fo, fn = _flatten(old), _flatten(new)
    for key in sorted(set(fo) | set(fn)):
        o, n = fo.get(key), fn.get(key)
        if o == n:
            continue
        entries.append(PolicyDiffEntry(field=key, old=o, new=n, classification=_classify(key, o, n)))

    # Restricted lists: element-wise (adding is tightening, removing is loosening).
    for attr, prefix in (("never_trade", "restricted.never_trade"),
                         ("warn_list", "restricted.warn_list")):
        old_set = set(getattr(old.restricted, attr))
        new_set = set(getattr(new.restricted, attr))
        for sym in sorted(new_set - old_set):
            entries.append(PolicyDiffEntry(field=prefix, old=None, new=sym, classification="tightening"))
        for sym in sorted(old_set - new_set):
            entries.append(PolicyDiffEntry(field=prefix, old=sym, new=None, classification="loosening"))
    return entries


# --------------------------------------------------------------------------- #
# Deep-merge for `changes` (setting a value to None removes it)               #
# --------------------------------------------------------------------------- #


def _deep_merge(base: dict, patch: dict) -> dict:
    out = copy.deepcopy(base)
    for k, v in patch.items():
        if v is None:
            out.pop(k, None)
        elif isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


# --------------------------------------------------------------------------- #
# Public entry point                                                          #
# --------------------------------------------------------------------------- #


def generate_risk_policy(
    mode: str = "create",
    *,
    preset: str | None = None,
    fields: dict | None = None,
    changes: dict | None = None,
    confirm: bool = False,
    policy_path: str | None = None,
    home: str | None = None,
    now: datetime | None = None,
) -> PolicyResult:
    now = now or datetime.now(timezone.utc)
    today = now.date().isoformat()
    path = resolve_policy_path(policy_path, home)

    if mode == "create":
        return _create(preset, fields, confirm, path, today, now)
    if mode == "update":
        return _update(changes, confirm, path, today, now)
    if mode == "show":
        return _show(path)
    raise ValueError(f"unknown mode {mode!r} (expected create | update | show)")


def _build_result(mode: str, pol: Policy, path: Path, written: bool,
                  requires_confirmation: bool, message: str,
                  diff: list[PolicyDiffEntry] | None = None) -> PolicyResult:
    return PolicyResult(
        mode=mode,
        written=written,
        path=str(path),
        requires_confirmation=requires_confirmation,
        message=message,
        policy=policy_to_dict(pol),
        yaml=render_yaml(pol),
        summary=messages.policy_summary(pol),
        diff=diff,
    )


def _create(preset: str | None, fields: dict | None, confirm: bool,
            path: Path, today: str, now: datetime) -> PolicyResult:
    if path.exists():
        raise ValueError(
            f"a policy already exists at {path}; use mode='update' to change it "
            f"(create never overwrites an existing policy)"
        )
    preset_name = preset or DEFAULT_PRESET
    if preset_name not in PRESETS:
        raise ValueError(f"unknown preset {preset_name!r} (expected one of {sorted(PRESETS)})")

    merged = _deep_merge(PRESETS[preset_name], fields or {})
    merged.update(
        schema_version=1, revision=1, preset=preset_name,
        created_at=today, updated_at=today,
    )
    pol = Policy(**merged)  # strict validation (unknown fields raise)

    if confirm:
        atomic_write_text(path, render_yaml(pol))
        audited = audit.record(path, "policy_created", {"revision": 1, "preset": preset_name,
                                                        "path": str(path)}, now=now)
        if not audited:
            # A policy change we cannot audit breaks the "every change is logged"
            # guarantee, so fail closed: roll the write back rather than leave an
            # unaudited policy in place.
            try:
                path.unlink()
            except OSError:  # pragma: no cover - defensive
                pass
            raise RuntimeError(
                f"policy created at {path} but the audit log could not be written; "
                f"rolled the change back"
            )
        return _build_result("create", pol, path, True, False,
                             f"Policy created at {path} (revision 1).")
    return _build_result(
        "create", pol, path, False, True,
        "Proposed a new policy. Review the rules, then call again with confirm=true to write it.",
    )


def _update(changes: dict | None, confirm: bool, path: Path,
            today: str, now: datetime) -> PolicyResult:
    if not path.exists():
        raise ValueError(
            f"no policy exists at {path} to update; use mode='create' first"
        )
    if not changes:
        raise ValueError("update mode requires a non-empty 'changes' object")

    current = Policy(**(yaml.safe_load(path.read_text("utf-8")) or {}))
    merged = _deep_merge(policy_to_dict(current), changes)
    merged["schema_version"] = 1
    merged["created_at"] = current.created_at or today
    proposed = Policy(**merged)
    # Bump metadata after validation so revision/timestamps are authoritative.
    proposed = proposed.model_copy(update={"revision": current.revision + 1, "updated_at": today})

    diff = diff_policies(current, proposed)
    loosenings = [e for e in diff if e.classification == "loosening"]

    if not diff:
        return _build_result("update", current, path, False, False,
                             "No changes: the requested update matches the current policy.", diff=[])

    if confirm:
        # Archive the outgoing revision, then write the new one.
        hist = history_dir(path) / f"rev-{current.revision}.yaml"
        atomic_write_text(hist, render_yaml(current))
        atomic_write_text(path, render_yaml(proposed))
        audited = audit.record(path, "policy_updated", {
            "from_revision": current.revision,
            "to_revision": proposed.revision,
            "diff": [e.model_dump() for e in diff],
            "loosenings": [e.field for e in loosenings],
        }, now=now)
        if not audited:
            # Fail closed: restore the prior revision so an unauditable change does
            # not silently take effect.
            atomic_write_text(path, render_yaml(current))
            try:
                hist.unlink()
            except OSError:  # pragma: no cover - defensive
                pass
            raise RuntimeError(
                f"policy update at {path} could not be audited; reverted to "
                f"revision {current.revision}"
            )
        msg = f"Policy updated to revision {proposed.revision}."
        if loosenings:
            msg += f" Note: {len(loosenings)} change(s) RELAXED your guardrails."
        return _build_result("update", proposed, path, True, False, msg, diff=diff)

    if loosenings:
        fields_txt = ", ".join(e.field for e in loosenings)
        msg = (
            f"Proposed update relaxes {len(loosenings)} guardrail(s): {fields_txt}. "
            f"Confirm with the user, then call again with confirm=true to apply."
        )
    else:
        msg = "Proposed update. Call again with confirm=true to apply."
    return _build_result("update", proposed, path, False, True, msg, diff=diff)


def _show(path: Path) -> PolicyResult:
    if not path.exists():
        return PolicyResult(
            mode="show", written=False, path=str(path), requires_confirmation=False,
            message=f"No policy found at {path}. Create one with mode='create'.",
        )
    pol = Policy(**(yaml.safe_load(path.read_text("utf-8")) or {}))
    return _build_result("show", pol, path, False, False,
                        f"Current policy at {path} (revision {pol.revision}).")
